version: '3'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    networks: 
      - kafka-network
    ports: 
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks: 
      - kafka-network
    ports: 
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper
networks:
  kafka-network:
